# Generated by Django 5.0.4 on 2024-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
