# Generated by Django 5.0.4 on 2024-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_lot_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lot',
            name='next_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
