# Generated by Django 5.0.4 on 2024-06-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_lot_current_bid_lot_next_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='start_price',
        ),
    ]
