# Generated by Django 5.0.4 on 2024-06-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_remove_lot_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='strike_count',
            field=models.IntegerField(default=0),
        ),
    ]
